services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes: [qdrant_data:/qdrant/storage]

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ollama_data:/root/.ollama]

  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      QDRANT_HOST: qdrant
      OLLAMA_URL: http://ollama:11434
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
