services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes: [qdrant_data:/qdrant/storage]

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ollama_data:/root/.ollama]

  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      QDRANT_HOST: qdrant
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: tinyllama:1.1b
      PROMPT_LIMIT: "20000"
      OLLAMA_TIMEOUT: "300"
      EMB_MODEL: "BAAI/bge-base-en-v1.5"
      SCORE_THRESHOLD: "0.35"
      FORCE_RECREATE: "false"            # no longer recreate every boot
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_data:
